CREATE OR REPLACE PROCEDURE USP_DOANHNGHIEP_GET_LIST_DN_FOR_XAC_THUC(
    P_RES OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT MADN, TENDN
        FROM DOANHNGHIEP
        WHERE TRANGTHAI = 0;
END;
/
GRANT EXECUTE ON USP_DOANHNGHIEP_GET_LIST_DN_FOR_XAC_THUC TO RL_NHANVIEN;


CREATE OR REPLACE PROCEDURE USP_DOANHNGHIEP_GET_DETAIL(
    P_MADN IN VARCHAR2,
    P_RES OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM DOANHNGHIEP
        WHERE MADN = P_MADN;
END;
/
GRANT EXECUTE ON USP_DOANHNGHIEP_GET_DETAIL TO RL_NHANVIEN;



CREATE OR REPLACE PROCEDURE USP_DOANHNGHIEP_TU_CHOI_DN(P_MADN IN VARCHAR2)
AUTHID DEFINER
AS
BEGIN
    EXECUTE IMMEDIATE ('DROP USER ' || P_MADN);
    DELETE FROM DOANHNGHIEP WHERE MADN = P_MADN;
END;
/
GRANT EXECUTE ON USP_DOANHNGHIEP_TU_CHOI_DN TO RL_NHANVIEN;



CREATE OR REPLACE PROCEDURE USP_DOANHNGHIEP_XAC_NHAN_DN(
    P_MADN IN VARCHAR2,
    P_TENDN IN NVARCHAR2,
    P_MSTHUE IN VARCHAR2,
    P_NGDAIDIEN IN NVARCHAR2,
    P_DIACHI IN NVARCHAR2
)
AUTHID DEFINER
AS
BEGIN
    EXECUTE IMMEDIATE ('ALTER USER ' || P_MADN || ' ACCOUNT UNLOCK');
    
    UPDATE DOANHNGHIEP
    SET 
        TENDN = P_TENDN,
        MSTHUE = P_MSTHUE,
        NGDAIDIEN = P_NGDAIDIEN,
        DIACHI = P_DIACHI,
        TRANGTHAI = 1
    WHERE MADN = P_MADN;
END;
/
GRANT EXECUTE ON USP_DOANHNGHIEP_XAC_NHAN_DN TO RL_NHANVIEN;
