CREATE OR REPLACE PROCEDURE USP_GIAYTO_INSERT(
    P_MAHOPDONG IN VARCHAR2,
    P_LOAI IN VARCHAR2,
    P_NOIDUNG IN VARCHAR2
)
AS
BEGIN
    INSERT INTO GIAYTOUV
    VALUES (SYS_CONTEXT('USERENV', 'SESSION_USER'), P_MAHOPDONG, P_LOAI, P_NOIDUNG);
END;
/
GRANT EXECUTE ON USP_GIAYTO_INSERT TO RL_UNGVIEN;

CREATE OR REPLACE PROCEDURE USP_GIAYTO_GET_BY_MAUV_MAHOPDONG(
    P_RES OUT SYS_REFCURSOR,
    P_MAUV IN VARCHAR2,
    P_MAHOPDONG IN VARCHAR2
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT LOAI, NOIDUNG
        FROM GIAYTOUV
        WHERE MAUV = P_MAUV AND MAHOPDONG = P_MAHOPDONG;
END;
/
GRANT EXECUTE ON USP_GIAYTO_GET_BY_MAUV_MAHOPDONG TO PUBLIC;



