CREATE OR REPLACE PROCEDURE USP_HINHTHUC_GET_ALL(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM HINHTHUC;
END;
/
GRANT EXECUTE ON USP_HINHTHUC_GET_ALL TO RL_DOANHNGHIEP;

select * from hinhthuc;