CREATE OR REPLACE PROCEDURE USP_HOADON_GET_BY_MAHOADON(P_RES OUT SYS_REFCURSOR, vMAHOPDONG IN VARCHAR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT * FROM HOADON
        WHERE MAHOPDONG = vMAHOPDONG;
END;
/
GRANT EXECUTE ON USP_HOADON_GET_BY_MAHOADON TO RL_NHANVIEN;


CREATE OR REPLACE PROCEDURE USP_HOADON_THANH_TOAN
(
    vSOTIEN IN FLOAT,
    vHINHTHUCTT IN NVARCHAR2,
    vMAHOPDONG IN VARCHAR2
)
AS
    vMAHOADON VARCHAR(10);
    vUSER VARCHAR(10) := SYS_CONTEXT('USERENV', 'SESSION_USER');
BEGIN
    SELECT TO_CHAR(COUNT(*) + 1) INTO vMAHOADON
    FROM HOADON;
    
    SELECT 'HD' || LPAD(vMAHOADON, 9 - LENGTH(vMAHOADON), '0') INTO vMAHOADON
    FROM (
      SELECT vMAHOADON
      FROM DUAL
    );

    INSERT INTO HOADON
    VALUES(vMAHOADON, SYSDATE, vSOTIEN, vHINHTHUCTT, vUSER, vMAHOPDONG);
    
    UPDATE HOPDONG
    SET TIENCONLAI = TIENCONLAI - vSOTIEN
    WHERE MAHOPDONG = vMAHOPDONG;
END;
/
GRANT EXECUTE ON USP_HOADON_THANH_TOAN TO RL_NHANVIEN;