CREATE OR REPLACE PROCEDURE USP_HOPDONG_GET_ALL_FOR_DUYETHS(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        WITH HOPDONG_FILTERED AS (
            SELECT MAHOPDONG, CAPBACTD, VITRITD, NGAYTD, THOIGIANTD
            FROM HOPDONG
            WHERE (NGAYTD + THOIGIANTD) <= (SYSDATE + 50)
        ),
        HSUNGTUYEN_OF_HOPDONG AS (
            SELECT HSUT.MAHOPDONG, COUNT(HSUT.MAHOPDONG) AS SOLUONGHS
            FROM HSUNGTUYEN HSUT
            JOIN HOPDONG_FILTERED HD ON HSUT.MAHOPDONG = HD.MAHOPDONG
            WHERE HSUT.KETQUA >= 2 AND HSUT.KETQUA <= 4
            GROUP BY HSUT.MAHOPDONG
        )
        SELECT HD.MAHOPDONG, CB.MOTA AS CAPBACTD, VT.MOTA AS VITRITD, 
        HD.NGAYTD, HD.THOIGIANTD, HSUT.SOLUONGHS
        FROM HOPDONG_FILTERED HD
        JOIN HSUNGTUYEN_OF_HOPDONG HSUT ON HD.MAHOPDONG = HSUT.MAHOPDONG
        JOIN CAPBAC CB ON HD.CAPBACTD = CB.MACB
        JOIN VITRI VT ON HD.VITRITD = VT.MAVT;
END;
/
GRANT EXECUTE ON USP_HOPDONG_GET_ALL_FOR_DUYETHS TO RL_NHANVIEN;




CREATE OR REPLACE PROCEDURE USP_HOPDONG_GET_ALL_FOR_PHANHOIHS(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        WITH HOPDONG_FILTERED AS (
            SELECT MAHOPDONG, CAPBACTD, VITRITD, NGAYTD, THOIGIANTD
            FROM HOPDONG
            WHERE (NGAYTD + THOIGIANTD) <= (SYSDATE + 50)
        ),
        HSUNGTUYEN_OF_HOPDONG AS (
            SELECT HSUT.MAHOPDONG, COUNT(HSUT.MAHOPDONG) AS SOLUONGHS
            FROM HSUNGTUYEN HSUT
            JOIN HOPDONG_FILTERED HD ON HSUT.MAHOPDONG = HD.MAHOPDONG
            WHERE HSUT.KETQUA >= 4 AND DOUUTIEN IS NOT NULL
            GROUP BY HSUT.MAHOPDONG
        )
        SELECT HD.MAHOPDONG, CB.MOTA AS CAPBACTD, VT.MOTA AS VITRITD, 
        HD.NGAYTD, HD.THOIGIANTD, HSUT.SOLUONGHS
        FROM HOPDONG_FILTERED HD
        JOIN HSUNGTUYEN_OF_HOPDONG HSUT ON HD.MAHOPDONG = HSUT.MAHOPDONG
        JOIN CAPBAC CB ON HD.CAPBACTD = CB.MACB
        JOIN VITRI VT ON HD.VITRITD = VT.MAVT;
END;
/
GRANT EXECUTE ON USP_HOPDONG_GET_ALL_FOR_PHANHOIHS TO RL_DOANHNGHIEP;




CREATE OR REPLACE PROCEDURE USP_HOPDONG_GET_TIEUCHIDN(
    P_RES OUT SYS_REFCURSOR,
    P_MAHOPDONG IN VARCHAR2
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT YEUCAU
        FROM HOPDONG
        WHERE MAHOPDONG = P_MAHOPDONG;
END;
/
GRANT EXECUTE ON USP_HOPDONG_GET_TIEUCHIDN TO RL_NHANVIEN, RL_DOANHNGHIEP;



CREATE OR REPLACE PROCEDURE USP_GET_LIST_TUYEN_DUNG(P_RES OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RES FOR
        SELECT HD.MAHOPDONG, VT.MOTA as VITRITD, DN.TENDN, CB.MOTA as CAPBACTD, DN.DIACHI, LISTAGG(KN.MOTA,', ') as KYNANG FROM HOPDONG HD JOIN DOANHNGHIEP DN ON HD.MADN = DN.MADN
                                                                                            JOIN CAPBAC CB ON HD.CAPBACTD = CB.MACB
                                                                                            JOIN VITRI VT ON HD.VITRITD = VT.MAVT
                                                                                            JOIN HOPDONG_KYNANG HDKN ON HD.MAHOPDONG = HDKN.MAHOPDONG
                                                                                            JOIN KYNANG KN ON HDKN.MAKN = KN.MAKN
        GROUP BY HD.MAHOPDONG, VT.MOTA, DN.TENDN, CB.MOTA, DN.DIACHI;
END;
/

GRANT EXECUTE ON USP_GET_LIST_TUYEN_DUNG TO RL_UNGVIEN;

CREATE OR REPLACE PROCEDURE USP_GET_LIST_TUYEN_DUNG_BY_NAME(P_RES OUT SYS_REFCURSOR, SearchString IN VARCHAR2)
AS
BEGIN
    OPEN P_RES FOR
        SELECT HD.MAHOPDONG, VT.MOTA as VITRITD, DN.TENDN, CB.MOTA AS CAPBACTD, DN.DIACHI, LISTAGG(KN.MOTA,', ') AS KYNANG FROM HOPDONG HD JOIN DOANHNGHIEP DN ON HD.MADN = DN.MADN
                                                                                            JOIN CAPBAC CB ON HD.CAPBACTD = CB.MACB
                                                                                            JOIN VITRI VT ON HD.VITRITD = VT.MAVT
                                                                                            JOIN HOPDONG_KYNANG HDKN ON HD.MAHOPDONG = HDKN.MAHOPDONG
                                                                                            JOIN KYNANG KN ON HDKN.MAKN = KN.MAKN
        WHERE VT.MOTA LIKE '%' ||SearchString || '%' OR DN.TENDN LIKE '%' ||SearchString || '%' OR KN.MOTA LIKE '%' ||SearchString || '%'
        GROUP BY HD.MAHOPDONG, VT.MOTA, DN.TENDN, CB.MOTA, DN.DIACHI;
END;
/
GRANT EXECUTE ON USP_GET_LIST_TUYEN_DUNG_BY_NAME TO RL_UNGVIEN;

CREATE OR REPLACE PROCEDURE USP_GET_DETAIL_TUYEN_DUNG(P_RES OUT SYS_REFCURSOR, MAHD IN VARCHAR2)
AS
BEGIN
    OPEN P_RES FOR
        SELECT HD.MAHOPDONG, HD.MADN, CB.MOTA AS CAPBACTD, VT.MOTA as VITRITD, HD.SOLUONGTD, HD.YEUCAU, HD.THOIGIANTD, HD.NGAYTD, DN.TENDN, DN.DIACHI, LISTAGG(KN.MOTA,', ') AS KYNANG, DN.EMAIL 
        FROM HOPDONG HD JOIN DOANHNGHIEP DN ON HD.MADN = DN.MADN
        JOIN CAPBAC CB ON HD.CAPBACTD = CB.MACB
        JOIN VITRI VT ON HD.VITRITD = VT.MAVT
        JOIN HOPDONG_KYNANG HDKN ON HD.MAHOPDONG = HDKN.MAHOPDONG
        JOIN KYNANG KN ON HDKN.MAKN = KN.MAKN
        WHERE HD.MAHOPDONG = MAHD
        GROUP BY HD.MAHOPDONG, VT.MOTA, DN.TENDN, CB.MOTA, DN.DIACHI, HD.MADN, HD.SOLUONGTD, HD.YEUCAU, HD.THOIGIANTD, HD.NGAYTD, DN.EMAIL;
END;
/
GRANT EXECUTE ON USP_GET_DETAIL_TUYEN_DUNG TO RL_UNGVIEN;