CREATE OR REPLACE PROCEDURE USP_HSUNGTUYEN_CHECK_APPLIED(
    P_RES OUT SYS_REFCURSOR,
    P_MAHOPDONG IN VARCHAR2
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT *
        FROM HSUNGTUYEN
        WHERE MAHOPDONG = P_MAHOPDONG
        FETCH FIRST 1 ROWS ONLY;
END;
/
GRANT EXECUTE ON USP_HSUNGTUYEN_CHECK_APPLIED TO RL_UNGVIEN;




CREATE OR REPLACE PROCEDURE USP_HSUNGTUYEN_INSERT(
    P_MAHOPDONG IN VARCHAR2,
    P_GIOITHIEU IN VARCHAR2,
    P_HOCVAN IN VARCHAR2,
    P_KINHNGHIEM IN VARCHAR2
)
AS
BEGIN
    INSERT INTO HSUNGTUYEN (MAUV, MAHOPDONG, NGAYNOP, GIOITHIEU,  HOCVAN, KINHNGHIEM, KETQUA)
    VALUES (SYS_CONTEXT('USERENV', 'SESSION_USER'), P_MAHOPDONG, SYSDATE, P_GIOITHIEU, P_HOCVAN, P_KINHNGHIEM, 0);
END;
/
GRANT EXECUTE ON USP_HSUNGTUYEN_INSERT TO RL_UNGVIEN;




CREATE OR REPLACE PROCEDURE USP_HSUNGTUYEN_GET_FOR_DUYETHS_BY_KETQUA(
    P_RES OUT SYS_REFCURSOR,
    P_MAHOPDONG IN VARCHAR2,
    P_KETQUA IN NUMBER
)
AS
BEGIN
    OPEN P_RES FOR
        WITH HSUNGTUYEN_FILTERED AS (
            SELECT MAUV, NGAYNOP, DOUUTIEN, CASE
                WHEN KETQUA = 2 THEN N'Đang chờ duyệt'
                WHEN KETQUA = 3 THEN N'Không đủ điều kiện' 
                WHEN KETQUA = 4 AND DOUUTIEN IS NULL THEN N'Cần sắp xếp độ ưu tiên'
                WHEN KETQUA = 4 AND DOUUTIEN IS NOT NULL THEN N'Đã sắp xếp độ ưu tiên'
                END AS KETQUA
            FROM HSUNGTUYEN
            WHERE MAHOPDONG = P_MAHOPDONG 
            AND KETQUA = P_KETQUA
        )
        SELECT HSUT.*, UV.HOTEN
        FROM HSUNGTUYEN_FILTERED HSUT
        JOIN UNGVIEN UV ON HSUT.MAUV = UV.MAUV
        ORDER BY HSUT.DOUUTIEN, HSUT.MAUV;
END;
/

GRANT EXECUTE ON USP_HSUNGTUYEN_GET_FOR_DUYETHS_BY_KETQUA TO RL_NHANVIEN;



CREATE OR REPLACE PROCEDURE USP_HSUNGTUYEN_GET_FOR_PHANHOIHS_BY_KETQUA(
    P_RES OUT SYS_REFCURSOR,
    P_MAHOPDONG IN VARCHAR2,
    P_KETQUA IN NUMBER
)
AS
BEGIN
    OPEN P_RES FOR
        WITH HSUNGTUYEN_FILTERED AS (
            SELECT MAUV, NGAYNOP, DOUUTIEN, CASE
                WHEN KETQUA = 4 THEN N'Đang chờ phản hồi'
                WHEN KETQUA = 6 THEN N'Đã đạt'
                END AS KETQUA
            FROM HSUNGTUYEN
            WHERE MAHOPDONG = P_MAHOPDONG 
            AND KETQUA = P_KETQUA AND DOUUTIEN IS NOT NULL
        )
        SELECT HSUT.*, UV.HOTEN
        FROM HSUNGTUYEN_FILTERED HSUT
        JOIN UNGVIEN UV ON HSUT.MAUV = UV.MAUV
        ORDER BY HSUT.DOUUTIEN, HSUT.MAUV;
END;
/

GRANT EXECUTE ON USP_HSUNGTUYEN_GET_FOR_PHANHOIHS_BY_KETQUA TO RL_DOANHNGHIEP;



CREATE OR REPLACE PROCEDURE USP_HSUNGTUYEN_GET_CHITIET_HSUNGTUYEN(
    P_RES OUT SYS_REFCURSOR,
    P_MAUV IN VARCHAR2,
    P_MAHOPDONG IN VARCHAR2
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT GIOITHIEU, HOCVAN, KINHNGHIEM
        FROM HSUNGTUYEN
        WHERE MAUV = P_MAUV AND MAHOPDONG = P_MAHOPDONG;
END;
/
GRANT EXECUTE ON USP_HSUNGTUYEN_GET_CHITIET_HSUNGTUYEN TO RL_NHANVIEN, RL_DOANHNGHIEP;


CREATE OR REPLACE PROCEDURE USP_HSUNGTUYEN_UPDATE_KETQUA(
    P_MAUV IN VARCHAR2,
    P_MAHOPDONG IN VARCHAR2,
    P_KETQUA IN NUMBER
)
AS
BEGIN
    UPDATE HSUNGTUYEN
    SET KETQUA = P_KETQUA
    WHERE MAUV = P_MAUV AND MAHOPDONG = P_MAHOPDONG;
END;
/
GRANT EXECUTE ON USP_HSUNGTUYEN_UPDATE_KETQUA TO RL_NHANVIEN, RL_DOANHNGHIEP;



CREATE OR REPLACE PROCEDURE USP_HSUNGTUYEN_UPDATE_DOUUTIEN(
    P_MAUV IN VARCHAR2,
    P_MAHOPDONG IN VARCHAR2,
    P_DOUUTIEN IN NUMBER
)
AS
BEGIN

    UPDATE HSUNGTUYEN
    SET DOUUTIEN = P_DOUUTIEN
    WHERE MAUV = P_MAUV AND MAHOPDONG = P_MAHOPDONG;
END;
/
GRANT EXECUTE ON USP_HSUNGTUYEN_UPDATE_DOUUTIEN TO RL_NHANVIEN;
