CREATE OR REPLACE PROCEDURE USP_NVPHANHOI_INSERT(
    P_MAUV IN VARCHAR2,
    P_MAHOPDONG IN VARCHAR2,
    P_NOIDUNG IN NVARCHAR2
)
AS
BEGIN
    INSERT INTO NVPHANHOI VALUES(P_MAUV, P_MAHOPDONG, SYSDATE, P_NOIDUNG);
    
    UPDATE HSUNGTUYEN 
    SET
        KETQUA = 1
    WHERE MAUV = P_MAUV
    AND MAHOPDONG = P_MAHOPDONG;
END;
/
GRANT EXECUTE ON USP_NVPHANHOI_INSERT TO RL_NHANVIEN;


CREATE OR REPLACE PROCEDURE USP_NVPHANHOI_GET_NEW(
    P_MAUV IN VARCHAR2,
    P_MAHOPDONG IN VARCHAR2,
    P_RES OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT NOIDUNG
        FROM NVPHANHOI
        WHERE MAUV = P_MAUV
        AND MAHOPDONG = P_MAHOPDONG
        ORDER BY NGAYPH DESC
        FETCH FIRST 1 ROWS ONLY;
END;
/
GRANT EXECUTE ON USP_NVPHANHOI_GET_NEW TO RL_UNGVIEN;
