CREATE OR REPLACE PROCEDURE USP_NVPHANHOI_INSERT(
    P_MAUV IN VARCHAR2,
    P_MAHOPDONG IN VARCHAR2,
    P_NOIDUNG IN NVARCHAR2
)
AS
BEGIN
    INSERT INTO NVPHANHOI VALUES(P_MAUV, P_MAHOPDONG, SYSDATE, P_NOIDUNG);
    
    UPDATE HSUNGTUYEN 
    SET
        KETQUA = 1
    WHERE MAUV = P_MAUV
    AND MAHOPDONG = P_MAHOPDONG;
END;
/
GRANT EXECUTE ON USP_NVPHANHOI_INSERT TO RL_NHANVIEN;