CREATE OR REPLACE PROCEDURE USP_UNGVIEN_GET_TTUNGTUYEN_BY_MAUV(
    P_RES OUT SYS_REFCURSOR,
    P_MAUV IN VARCHAR2
)
AS
BEGIN
    OPEN P_RES FOR
        SELECT HOTEN, EMAIL, SDT
        FROM UNGVIEN
        WHERE MAUV = P_MAUV;
END;
/
GRANT EXECUTE ON USP_UNGVIEN_GET_TTUNGTUYEN_BY_MAUV TO PUBLIC;
