--DOANHNGHIEP

GRANT SELECT ON DOANHNGHIEP TO RL_DOANHNGHIEP;

GRANT SELECT, INSERT ON HOPDONG TO RL_DOANHNGHIEP;
GRANT UPDATE (TRANGTHAI) ON HOPDONG TO RL_DOANHNGHIEP;

GRANT SELECT ON CAPBAC TO RL_DOANHNGHIEP;

GRANT SELECT ON VITRI TO RL_DOANHNGHIEP;

GRANT SELECT ON KYNANG TO RL_DOANHNGHIEP;

GRANT SELECT ON HINHTHUC TO RL_DOANHNGHIEP;

GRANT SELECT, INSERT ON HINHTHUC_HOPDONG TO RL_DOANHNGHIEP;

GRANT SELECT, INSERT ON HOPDONG_KYNANG TO RL_DOANHNGHIEP;

GRANT SELECT, INSERT ON DNPHANHOI TO RL_DOANHNGHIEP;

GRANT SELECT ON UUDAI TO RL_DOANHNGHIEP;

GRANT SELECT ON HOADON TO RL_DOANHNGHIEP;

GRANT SELECT ON HSUNGTUYEN TO RL_DOANHNGHIEP;
GRANT UPDATE (KETQUA) ON HSUNGTUYEN TO RL_DOANHNGHIEP;

GRANT SELECT ON UNGVIEN TO RL_DOANHNGHIEP;

GRANT SELECT ON GIAYTOUV TO RL_DOANHNGHIEP;






-- UNGVIEN

GRANT SELECT ON UNGVIEN TO RL_UNGVIEN;

GRANT SELECT, INSERT ON HSUNGTUYEN TO RL_UNGVIEN;
GRANT UPDATE (GIOITHIEU, HOCVAN, KINHNGHIEM, KETQUA) ON HSUNGTUYEN TO RL_UNGVIEN;

GRANT SELECT, INSERT, DELETE ON GIAYTOUV TO RL_UNGVIEN;
GRANT UPDATE (LOAI, NOIDUNG) ON GIAYTOUV TO RL_UNGVIEN;

GRANT SELECT ON NVPHANHOI TO RL_UNGVIEN;

GRANT SELECT ON HOPDONG TO RL_UNGVIEN;

GRANT SELECT ON HINHTHUC_HOPDONG TO RL_UNGVIEN;

GRANT SELECT ON HOPDONG_KYNANG TO RL_UNGVIEN;

GRANT SELECT ON HINHTHUC TO RL_UNGVIEN;

GRANT SELECT ON KYNANG TO RL_UNGVIEN;

GRANT SELECT ON CAPBAC TO RL_UNGVIEN;

GRANT SELECT ON VITRI TO RL_UNGVIEN;

GRANT SELECT ON DOANHNGHIEP TO RL_UNGVIEN;







-- NHANVIEN

GRANT SELECT ON NHANVIEN TO RL_NHANVIEN;

GRANT SELECT, INSERT ON HOADON TO RL_NHANVIEN;

GRANT SELECT, INSERT ON HOPDONG TO RL_NHANVIEN;
GRANT UPDATE(YEUCAU, THOIGIANTD, NGAYTD, TRANGTHAI, TONGTIEN, TIENCONLAI) ON HOPDONG TO RL_NHANVIEN;

GRANT SELECT ON CAPBAC TO RL_NHANVIEN;

GRANT SELECT ON VITRI TO RL_NHANVIEN;

GRANT SELECT ON KYNANG TO RL_NHANVIEN;

GRANT SELECT ON HINHTHUC TO RL_NHANVIEN;

GRANT SELECT, INSERT ON HINHTHUC_HOPDONG TO RL_NHANVIEN;

GRANT SELECT, INSERT ON HOPDONG_KYNANG TO RL_NHANVIEN;

GRANT SELECT ON DNPHANHOI TO RL_NHANVIEN;

GRANT SELECT, INSERT ON UUDAI TO RL_NHANVIEN;

GRANT SELECT ON HSUNGTUYEN TO RL_NHANVIEN;
GRANT UPDATE (KETQUA, DOUUTIEN) ON HSUNGTUYEN TO RL_NHANVIEN;

GRANT SELECT ON UNGVIEN TO RL_NHANVIEN;

GRANT SELECT ON DOANHNGHIEP TO RL_NHANVIEN;
GRANT UPDATE (TRANGTHAI) ON DOANHNGHIEP TO RL_NHANVIEN;






-- BANLANHDAO

BEGIN
    FOR TB IN (
        SELECT TABLE_NAME
        FROM USER_TABLES
    )
    LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON ' || TB.TABLE_NAME || ' TO RL_BANLANHDAO';
    END LOOP;
END;
/

GRANT INSERT ON UUDAI TO RL_BANLANHDAO;



