ALTER SESSION SET CONTAINER=PTTK;

-- DROP ROLE
DROP ROLE RL_NHANVIEN;
DROP ROLE RL_BANLANHDAO;
DROP ROLE RL_DOANHNGHIEP;
DROP ROLE RL_UNGVIEN;

-- CREATE ROLE
CREATE ROLE RL_NHANVIEN;
CREATE ROLE RL_BANLANHDAO;
CREATE ROLE RL_DOANHNGHIEP;
CREATE ROLE RL_UNGVIEN;

-- DROP USERS
SET SERVEROUTPUT ON;
EXEC USP_DROP_USER_LIST;

-- CREATE USERS
EXEC USP_CREATE_USER_LIST;


-- Lấy role chính của một user
CREATE OR REPLACE FUNCTION USP_GET_USER_MAIN_ROLE
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) DEFAULT '';
BEGIN
    P_USER_ROLE := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF P_USER_ROLE = 'C##ADMIN' THEN
        RETURN 'DBA';
    END IF;
    
    SELECT GRANTED_ROLE INTO P_USER_ROLE
    FROM DBA_ROLE_PRIVS
    WHERE GRANTEE = P_USER_ROLE
    AND GRANTED_ROLE LIKE 'RL%';
    
    RETURN P_USER_ROLE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'RL_NONE';
END;
/
GRANT EXECUTE ON USP_GET_USER_MAIN_ROLE TO PUBLIC;




