ALTER SESSION SET CONTAINER=PTTK;

-- Tạo user
CREATE OR REPLACE PROCEDURE USP_CREATE_USER (
    P_USERNAME IN VARCHAR2,
    P_PASSWORD IN VARCHAR2
)
AS
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER ' || P_USERNAME || ' IDENTIFIED BY ' || P_PASSWORD;
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || P_USERNAME;
END;
/

-- Drop list user hiện tại
CREATE OR REPLACE PROCEDURE USP_DROP_USER_LIST
AS
    CURSOR CUR_UV IS(
        SELECT MAUV
        FROM UNGVIEN
    );
        
    CURSOR CUR_DN IS(
        SELECT MADN
        FROM DOANHNGHIEP
    );
        
    CURSOR CUR_NV IS( 
        SELECT MANV
        FROM NHANVIEN
    );
        
    STRSQL VARCHAR(5000);
    P_USER VARCHAR2(50);
BEGIN
    OPEN CUR_UV;
    LOOP
        FETCH CUR_UV INTO P_USER;
        EXIT WHEN CUR_UV%NOTFOUND;
        
        STRSQL := 'DROP USER ' || P_USER;
        EXECUTE IMMEDIATE STRSQL;
    END LOOP;
    CLOSE CUR_UV;
    
    OPEN CUR_DN;
    LOOP
        FETCH CUR_DN INTO P_USER;
        EXIT WHEN CUR_DN%NOTFOUND;
        
        STRSQL := 'DROP USER ' || P_USER;
        EXECUTE IMMEDIATE STRSQL;
    END LOOP;
    CLOSE CUR_DN;
    
    OPEN CUR_NV;
    LOOP
        FETCH CUR_NV INTO P_USER;
        EXIT WHEN CUR_NV%NOTFOUND;
        
        STRSQL := 'DROP USER ' || P_USER;
        EXECUTE IMMEDIATE STRSQL;
    END LOOP;
    CLOSE CUR_NV;
END;
/




-- Tạo list user cho database
CREATE OR REPLACE PROCEDURE USP_CREATE_USER_LIST
AS
    CURSOR CUR_UV IS (
        SELECT MAUV
        FROM UNGVIEN
    );
    CURSOR CUR_DN IS (
        SELECT MADN
        FROM DOANHNGHIEP
    );
    CURSOR CUR_NV IS (
        SELECT MANV, VAITRO
        FROM NHANVIEN
    );
    STRSQL VARCHAR2(5000);
    P_USER VARCHAR2(50);
    P_ROLE NUMBER(1, 0);
BEGIN
    OPEN CUR_UV;
    LOOP
        FETCH CUR_UV INTO P_USER;
        EXIT WHEN CUR_UV%NOTFOUND;
        
        USP_CREATE_USER(P_USER, '123');        
        EXECUTE IMMEDIATE ('GRANT RL_UNGVIEN TO ' || P_USER);
    END LOOP;
    CLOSE CUR_UV;
    
    OPEN CUR_DN;
    LOOP
        FETCH CUR_DN INTO P_USER;
        EXIT WHEN CUR_DN%NOTFOUND;
        
        USP_CREATE_USER(P_USER, '123');        
        EXECUTE IMMEDIATE ('GRANT RL_DOANHNGHIEP TO ' || P_USER);
    END LOOP;
    CLOSE CUR_DN;
    
    OPEN CUR_NV;
    LOOP
        FETCH CUR_NV INTO P_USER, P_ROLE;
        EXIT WHEN CUR_NV%NOTFOUND;
        
        USP_CREATE_USER(P_USER, '123');
        
        IF P_ROLE = 0 THEN 
            EXECUTE IMMEDIATE ('GRANT RL_NHANVIEN TO ' || P_USER);
        ELSIF P_ROLE = 1 THEN
            EXECUTE IMMEDIATE ('GRANT RL_BANLANHDAO TO ' || P_USER);
    
        END IF;
    END LOOP;
    CLOSE CUR_NV;
END; 
/