-- COMMON FUNCTION



-- DOANHNGHIEP

-- Doanh nghiệp chỉ được xem thông tin của chính mình trên bảng DOANHNGHIEP
CREATE OR REPLACE FUNCTION VPD_POL_FUNC_GET_BY_MADN(
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) DEFAULT '';
BEGIN
    P_USER_ROLE := USP_GET_USER_MAIN_ROLE;
    
    IF P_USER_ROLE = 'RL_DOANHNGHIEP' THEN
        RETURN 'MADN = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''';
    ELSE
        RETURN '1 = 1';
    END IF;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'DOANHNGHIEP',
        POLICY_NAME => 'VPD_POL_DOANHNGHIEP_GET_BY_MADN'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOPDONG',
        POLICY_NAME => 'VPD_POL_HOPDONG_GET_BY_MADN'
    );
END;
/


BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'DOANHNGHIEP',
        POLICY_NAME => 'VPD_POL_DOANHNGHIEP_GET_BY_MADN',
        POLICY_FUNCTION => 'VPD_POL_FUNC_GET_BY_MADN',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOPDONG',
        POLICY_NAME => 'VPD_POL_HOPDONG_GET_BY_MADN',
        POLICY_FUNCTION => 'VPD_POL_FUNC_GET_BY_MADN',
        STATEMENT_TYPES => 'SELECT, INSERT, UPDATE',
        UPDATE_CHECK  => TRUE
    );
END;
/

-- Doanh nghiệp chỉ được XEM, THÊM CÁC thông tin liên quan đến chính mình trên bảng
-- HINHTHUC_HOPDONG, HOPDONG_KYNANG, DNPHANHOI, UUDAI, HOADON, HSUNGTUYEN
CREATE OR REPLACE FUNCTION VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP(
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) DEFAULT '';
    P_USER_ID VARCHAR2(20) DEFAULT '';
BEGIN
    P_USER_ROLE := USP_GET_USER_MAIN_ROLE;
    
    IF P_USER_ROLE = 'RL_DOANHNGHIEP' THEN
        RETURN 'MAHOPDONG IN (SELECT MAHOPDONG FROM HOPDONG)';
    ELSE
        RETURN '1 = 1';
    END IF;
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HINHTHUC_HOPDONG',
        POLICY_NAME => 'VPD_POL_HINHTHUC_HOPDONG_OF_DOANHNGHIEP'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOPDONG_KYNANG',
        POLICY_NAME => 'VPD_POL_HOPDONG_KYNANG_OF_DOANHNGHIEP'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'DNPHANHOI',
        POLICY_NAME => 'VPD_POL_DNPHANHOI_OF_DOANHNGHIEP'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'UUDAI',
        POLICY_NAME => 'VPD_POL_UUDAI_OF_DOANHNGHIEP'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOADON',
        POLICY_NAME => 'VPD_POL_HOADON_OF_DOANHNGHIEP'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HSUNGTUYEN',
        POLICY_NAME => 'VPD_POL_HSUNGTUYEN_OF_DOANHNGHIEP'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'GIAYTOUV',
        POLICY_NAME => 'VPD_POL_GIAYTOUV_OF_DOANHNGHIEP'
    );
END;
/


BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HINHTHUC_HOPDONG',
        POLICY_NAME => 'VPD_POL_HINHTHUC_HOPDONG_OF_DOANHNGHIEP',
        POLICY_FUNCTION => 'VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP',
        STATEMENT_TYPES => 'SELECT, INSERT',
        UPDATE_CHECK => TRUE
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOPDONG_KYNANG',
        POLICY_NAME => 'VPD_POL_HOPDONG_KYNANG_OF_DOANHNGHIEP',
        POLICY_FUNCTION => 'VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP',
        STATEMENT_TYPES => 'SELECT, INSERT',
        UPDATE_CHECK => TRUE
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'DNPHANHOI',
        POLICY_NAME => 'VPD_POL_DNPHANHOI_OF_DOANHNGHIEP',
        POLICY_FUNCTION => 'VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP',
        STATEMENT_TYPES => 'SELECT, INSERT',
        UPDATE_CHECK => TRUE
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'UUDAI',
        POLICY_NAME => 'VPD_POL_UUDAI_OF_DOANHNGHIEP',
        POLICY_FUNCTION => 'VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HOADON',
        POLICY_NAME => 'VPD_POL_HOADON_OF_DOANHNGHIEP',
        POLICY_FUNCTION => 'VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HSUNGTUYEN',
        POLICY_NAME => 'VPD_POL_HSUNGTUYEN_OF_DOANHNGHIEP',
        POLICY_FUNCTION => 'VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP',
        STATEMENT_TYPES => 'SELECT, UPDATE',
        UPDATE_CHECK => TRUE
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'GIAYTOUV',
        POLICY_NAME => 'VPD_POL_GIAYTOUV_OF_DOANHNGHIEP',
        POLICY_FUNCTION => 'VPD_POL_FUNC_MAHOPDONG_OF_DOANHNGHIEP',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/




-- UNGVIEN

CREATE OR REPLACE FUNCTION VPD_POL_FUNC_GET_BY_MAUV(
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) DEFAULT '';
BEGIN
    P_USER_ROLE := USP_GET_USER_MAIN_ROLE;
    
    IF P_USER_ROLE = 'RL_UNGVIEN' THEN
        RETURN 'MAUV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''';
    ELSE
        RETURN '1 = 1';
    END IF;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'UNGVIEN',
        POLICY_NAME => 'VPD_POL_UNGVIEN_GET_BY_MAUV'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HSUNGTUYEN',
        POLICY_NAME => 'VPD_POL_HSUNGTUYEN_GET_BY_MAUV'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'GIAYTOUV',
        POLICY_NAME => 'VPD_POL_GIAYTOUV_GET_BY_MAUV'
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'NVPHANHOI',
        POLICY_NAME => 'VPD_POL_NVPHANHOI_GET_BY_MAUV'
    );
END;
/



BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'UNGVIEN',
        POLICY_NAME => 'VPD_POL_UNGVIEN_GET_BY_MAUV',
        POLICY_FUNCTION => 'VPD_POL_FUNC_GET_BY_MAUV',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'HSUNGTUYEN',
        POLICY_NAME => 'VPD_POL_HSUNGTUYEN_GET_BY_MAUV',
        POLICY_FUNCTION => 'VPD_POL_FUNC_GET_BY_MAUV',
        STATEMENT_TYPES => 'SELECT, INSERT, UPDATE',
        UPDATE_CHECK  => TRUE
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'GIAYTOUV',
        POLICY_NAME => 'VPD_POL_GIAYTOUV_GET_BY_MAUV',
        POLICY_FUNCTION => 'VPD_POL_FUNC_GET_BY_MAUV',
        STATEMENT_TYPES => 'SELECT, INSERT, UPDATE',
        UPDATE_CHECK  => TRUE
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'NVPHANHOI',
        POLICY_NAME => 'VPD_POL_NVPHANHOI_GET_BY_MAUV',
        POLICY_FUNCTION => 'VPD_POL_FUNC_GET_BY_MAUV',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/



-- NHANVIEN
CREATE OR REPLACE FUNCTION VPD_POL_FUNC_GET_BY_MANV(
    P_SCHEMA IN VARCHAR2, 
    P_OBJECT IN VARCHAR2
)
RETURN VARCHAR2
AS
    P_USER_ROLE VARCHAR2(20) DEFAULT '';
BEGIN
    P_USER_ROLE := USP_GET_USER_MAIN_ROLE;
    
    IF P_USER_ROLE = 'RL_NHANVIEN' THEN
        RETURN 'MANV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''';
    ELSE
        RETURN '1 = 1';
    END IF;
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'NHANVIEN',
        POLICY_NAME => 'VPD_POL_NHANVIEN_GET_BY_MAUV'
    );
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'C##ADMIN',
        OBJECT_NAME => 'NHANVIEN',
        POLICY_NAME => 'VPD_POL_NHANVIEN_GET_BY_MANV',
        POLICY_FUNCTION => 'VPD_POL_FUNC_GET_BY_MANV',
        STATEMENT_TYPES => 'SELECT'
    );
END;
/
